name:                FuzzyModelling-Lab2
version:             0.1.0.0
github:              "petals-of-white/FuzzyModelling-Lab2"
license:             MIT
author:              "Maksym Syvash"
maintainer:          "maksym_syvash@outlook.com"
copyright:           "2024 Maksym Syvash"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/petals-of-white/FuzzyModelling-Lab2#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  FuzzyModelling-Lab2-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - FuzzyModelling-Lab2

tests:
  FuzzyModelling-Lab2-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - FuzzyModelling-Lab2
